# Install my dotfiles.
---
- name: dotfiles
  hosts: all
  vars_files:
  - vars.yml
  remote_user: "{{ username }}"
  tasks:

  - name: clone my dotfiles repo.
    git: repo=https://github.com/{{ github_user }}/dotfiles.git
         dest={{ home }}/.dotfiles

  - name: add an ssh remote
    template: src=templates/dotfiles-gitconfig dest={{ home }}/.dotfiles/.git/config
              mode=0644

  - name: generate the gitconfig template
    template: src=templates/gitconfig.j2 dest={{ home }}/.dotfiles/git/gitconfig.symlink
              mode=0644

  - name: install the symlinks.
    command: chdir={{ home }}/.dotfiles script/bootstrap
    environment:
      OVERWRITE_ALL: "true"
