---
- hosts: all
  remote_user: root
  vars_files:
  - vars.yml
  tasks:

  - include: account.yml tags=account

  - include: dotfiles.yml tags=account

  - include: ruby.yml tags=software,ruby

  - include: python.yml tags=software,python

  - include: node.yml tags=software,node

  - include: go.yml tags=software,go
